/*
 *
 * User constants
 *
 */

export const DEFAULT_ACTION = 'app/User/DEFAULT_ACTION';

export const SELECT_FEEDBACK_TEMPLATE_INFO_REQUEST = 'SELECT_FEEDBACK_TEMPLATE_INFO_REQUEST'
export const SELECT_FEEDBACK_TEMPLATE_INFO_SUCCESS = 'SELECT_FEEDBACK_TEMPLATE_INFO_SUCCESS'
export const SELECT_FEEDBACK_TEMPLATE_INFO_ERROR = 'SELECT_FEEDBACK_TEMPLATE_INFO_ERROR'